name: myserve

extra-source-files:
- README.md

dependencies:
- aeson
- base
- beam-core
- beam-postgres
- bytestring
- envy
- postgresql-simple
- resource-pool
- servant-server
- time
- warp
- wai
- text
- mtl
- network
- http-types
- case-insensitive
- uuid
- password

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unticked-promoted-constructors

library:
  source-dirs: src

executables:
  myserve-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myserve
