# the latest LTS snapshot that beam-postgres is a part of is 20.26
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/26.yaml

packages:
- .

extra-deps:
  - os-string-2.0.2

  - git: https://github.com/flipstone/orville
    commit: cf41ce07995597ba9c6c08658812ce2bd4abf313
    subdir: orville-postgresql